# Generated by Django 3.1.4 on 2020-12-13 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appservicios', '0002_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='clientes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appservicios.cliente'),
        ),
        migrations.AlterField(
            model_name='contratos',
            name='servicios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appservicios.servicios'),
        ),
    ]
